apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockerapp-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tanaysrivastav1/argocd-config
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true

