apiVersion: apps/v1
kind: Deployment
  metadata: testapp-deployment
spec:
  selector:
    matchLabels:
      app: testapp
    replicas: 2
    template:
      metadata:
        labels:
          app: testapp
      spec:
        containers:
          - name: testapp
            image: itsslumpbro/docker-stuff:latest
            ports:
            - containerPort: 8080